name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Run build script
        run: ./build.sh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/new_names.amd64
            release/new_names.arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
